name: 'Tests: eslint 9'

on: [pull_request, push]

jobs:
  eslint-9:
    name: 'eslint 9 (latest)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
      - run: npm install --no-save eslint@9
      - run: npm ls eslint
      - run: npm run tests-only
